<link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="//code.jquery.com/jquery-1.9.1.js"></script>
<script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script type="text/javascript">

jQuery.extend({
	getParams : function(str) {
		return (str || document.location.search).replace(/(^\?)/,'').split("&").map(function(n){return n = n.split("="),this[n[0]] = n[1],this}.bind({}))[0];
	}
});

jQuery( function( ) {

	jQuery( '#wpcsv-progressbar' ).progressbar( { value: 0 } );

	var retpercent = 0;
	var progress = 0;
	var base_url = '<?php echo site_url( ); ?>';
	function getProgress( progress, retpercent, export_id ) {	
		jQuery.ajax({
			url: base_url + '/wp-admin/admin-ajax.php?action=process_export',
			type: "GET",
			data: 'start=' + progress + '&progress=' + retpercent + '&export_id=' + export_id,
			dataType : 'json',
			success: function( data ) {
				var percentage = parseFloat( data.percentagecomplete );
				if ( percentage < 0 ) {
					jQuery( '#wpcsv-progressbar' ).addClass( 'ui-widget-content' ).removeClass( 'stripes' );
					jQuery( '#nothing-to-export' ).show( );
					jQuery( '#export_wrapper' ).hide( );
					jQuery( '#download_link' ).hide( );
				} else if ( percentage < 100 ) {
					jQuery( '#wpcsv-progressbar' ).progressbar( "value", percentage );
					jQuery( '#percent' ).text( '(' + percentage + '%)' );
					getProgress( data.position, data.percentagecomplete, export_id );
				} else {
					jQuery( '#wpcsv-progressbar' ).progressbar( "value", percentage );
					jQuery( '#percent' ).text( '(' + percentage + '%)' );
					jQuery( '#wpcsv-export-progress' ).hide( );
					jQuery( '#wpcsv-export-download' ).show( );
				}
			},
			error: function( data ) {
				alert( 'Export failed due to a server error.  Check the error log.' );
				jQuery( '#wpcsv-export-error' ).empty( );
				heading = '<h2>The following error was generated by your server:</h2>';
				ajax_response = '<p>' + data.responseText + '</p>';
				jQuery( '#wpcsv-export-error' ).html( heading + ajax_response );
				jQuery( '#wpcsv-export-error' ).show( );
				jQuery( '#download_link' ).hide( );
				jQuery( '#wpcsv-progressbar' ).progressbar( "value", 0 );
				jQuery( '#wpcsv-progressbar' ).addClass( 'ui-widget-content' ).removeClass( 'stripes' );
				window.clearInterval( interval_id );
				jQuery( '#percent' ).text( '(0%)' );
				return;
			}

		});
	}

	var params = jQuery.getParams( window.location.search );

	jQuery( '#start_export' ).on( 'click', function( ) {
		jQuery( '#download_link' ).hide( );
		jQuery( '#wpcsv-progressbar' ).progressbar( "value", 0 );
		jQuery( '#wpcsv-progressbar' ).removeClass( 'ui-widget-content' ).addClass( 'stripes' );
		getProgress( 0, 0, params['wpcsv_export_id'] );
	});
	
	jQuery( '.wpcsv-date' ).datepicker({
		changeYear: true,
		changeMonth: true,
		dateFormat: 'yy-mm-dd'
	});

	jQuery( '#wpcsv-restart-search' ).on( 'click', function( e ) {
		jQuery( '.wpcsv-panel' ).hide( );
		jQuery( '#wpcsv-export-generate' ).show( );
		e.preventDefault( );
		return false;
	});
	
	jQuery( '#wpcsv-download' ).on( 'click', function( e ) {
		window.location.href = '/?wpcsv_export=' + params['wpcsv_export_id'];
	});


	if ( typeof params['wpcsv_export_id'] != 'undefined' && params['wpcsv_export_id'] != '' ) {
		jQuery( '#wpcsv-export-generate' ).hide( );
		jQuery( '#wpcsv-progressbar' ).progressbar( "value", 0 );
		jQuery( '#wpcsv-progressbar' ).removeClass( 'ui-widget-content' ).addClass( 'stripes' );
		jQuery( '#wpcsv-export-progress' ).show( );
		getProgress( 0, 0, params['wpcsv_export_id'] );
	} else if ( typeof params['wpcsv_export_id'] == 'string' && params['wpcsv_export_id'] == '' ) {
		location.href = location.protocol + '//' + location.host + location.pathname;
	}
});

</script>

<form action='' method='GET'>
	<fieldset id='wpcsv-frontend-download'>
		<legend>CSV Export</legend>

		<div id='wpcsv-export-generate' class='wpcsv-panel'>
			<input name='wpcsv_export_id' type='hidden' value='<?php echo wp_create_nonce( 'wpcsv_frontend_export' ); ?>' />
			<label for='wpcsv-start-date'>Start: </label><input id='wpcsv-start-date' name='wpcsv_start_date' class='wpcsv-date' />
			<label for='wpcsv-end-date'>End: </label><input id='wpcsv-end-date' name='wpcsv_end_date' class='wpcsv-date' />
			<input type='submit' id='wpcsv-export-button' value='Start Export' />
		</div>
		<div id='wpcsv-export-progress' class='wpcsv-panel' style='display:none'>
			<div id="wpcsv-progressbar_holder"><div id="wpcsv-progressbar"></div></div><span id='percent'>(0%)</span>
		</div>
		<div id='wpcsv-export-download' class='wpcsv-panel' style='display:none'>
			<div id="wpcsv-download_link">
				<input type='button' id='wpcsv-download' value='Download' />
				<input type='button' id='wpcsv-restart-search' value='Restart' />
			</div>
		</div>
		<div id='wpcsv-export-error' class='wpcsv-panel' style='display:none'>
		</div>
	</fieldset>
</form>
